//
// Created by barba on 07/11/2024.
//

#include "ejercicio_6.h"
#include <iostream>
#include <stdexcept>

void lanzaExcepcion() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcion");
}